export {HomeScreen as HomeScreen} from './HomeScreen'
export {RecipeDeatils as RecipeDeatils} from './RecipeDetails'
export {Search as Search} from './Search'
export {SplashScreen as SplashScreen} from './SplashScreen'
export {Demo as Demo} from './Demo'
export {Login as Login} from './Login'
export {Signup as Signup} from './Signup'